### ISSUE TITLE
Need to implement mechanism for obtaining edit rights in *-che namespace

### ISSUE THREAD

**Issue by ibuziuk** [fabric8-services/fabric8-tenant#686]
need to implement mechanism that would allow to get edit rights for a particular user in their *-che namespace (edit rights in *-che namespace are required for developers). From the UX perspective mechanism should be the following:
- Dedicated feature toggle e.g. `che.edit.rights` with `userId` strategy enabled on prod / prod-preview
- `identity id` is added to the toggle 
- user presses `update tenant` from the profile page on `openshift.io` and edit rights are granted in the *-che namespace
- `identity id` is removed from the toggle
-   user presses `update tenant` from the profile page on `openshift.io` and edit rights are revoked from the *-che namespace

**Comment by MatousJobanek** [comment]
@ibuziuk sorry for long inactivity. Sadly, I haven't got to it yet because I got stuck by other issues with higher severity. 
I should start working on it after the New Year

**Comment by ibuziuk** [comment]
@MatousJobanek @alexeykazakov any plans to handle this issue in the nearest future ? (the issue is related to https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/844)

**Comment by MatousJobanek** [comment]
Hi @ibuziuk,

I have the implementation for this feature done, but I cannot push it to master for now. The reason is that the implementation is built on top of the new tenant core logic that is currently in the [develop](https://github.com/fabric8-services/fabric8-tenant/tree/develop) branch and is deployed to prod-preview to test it in a real environment. 
In other words, as soon as the new logic is stable, deeply tested and working for a few days without any problem, then I can merge it to master. And when it is merged then I can also make PR/merge the logic for dynamic adding/deletion of the edit rights.

Sorry for the delay. I hope that next week I could merge it.

**Comment by ibuziuk** [comment]
thanks for update @MatousJobanek !

**Comment by ibuziuk** [comment]
@MatousJobanek hi, could you please provide some updates regarding this issue. It now becomes pretty important due to the fact that https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/844 was closed

**Comment by alexeykazakov** [comment]
We are planning to merge https://github.com/fabric8-services/fabric8-tenant/pull/741 on Monday. It will fix this issue.

**Comment by MatousJobanek** [comment]
@ibuziuk it's been merged, could you please verify that it works as expected in prod-preview? If it doesn't, please ping me in MM. Thanks

**Comment by ibuziuk** [comment]
@MatousJobanek @alexeykazakov  could you please clarify what is the current flow for getting edit rights in `che` namespace for a particular user ? add identity to toggle and press the update tenant button ?

**Comment by ibuziuk** [comment]
@MatousJobanek seems to work just fine - great job \o/ Am I correct that this is already promoted to prod ?

**Comment by ibuziuk** [comment]
one thing I noticed - if identity is removed from toggle, update tenant does not seem to revoke edit rights. is it expected ?

**Comment by MatousJobanek** [comment]
@ibuziuk 
> could you please clarify what is the current flow for getting edit rights in `che` namespace for a particular user ? add identity to toggle and press the update tenant button ?

yes, this is exactly the expected flow

> seems to work just fine - great job \o/ Am I correct that this is already promoted to prod ?

thank you, but it is not promoted to prod for now :-). It's just in prod-preview - please, try it there

> one thing I noticed - if identity is removed from toggle, update tenant does not seem to revoke edit rights. is it expected ?

the tenant should revoke the edit rights when the identity is removed from the toggle. the behavior that you observe is because you are in prod and not prod-preview. In prod, there is still the original template with the edit rights contained in it

**Comment by ibuziuk** [comment]
tested on prod-preview - all works just fine \o/
huge +1 for promotion to prod

**Comment by MatousJobanek** [comment]
it's there @ibuziuk ;-) https://github.com/openshiftio/saas-openshiftio/commit/493bfab6c53d47d56c1e4fe1b33cb1c46a5f7a7d
